### ISSUE TITLE
pwm.deinit() and pwm.init()

### ISSUE THREAD

**Issue by vahithosan** [Wind-stormger/micropython-uasycio-buzzer#1]
Hi. Your library very good. Thanks for sharing. 
I try your code on esp32-wroom-32d. I connected buzzer gpio16. run example code and i cant hear any sound. when i write pwm.deinit() and pwm.init() i hear sound

```
from machine import Pin,PWM
import time
import buzzer
Musical_Score=[(1/8,"H5"),(1/8,"0"),(1/4,"H7")]
pwm=PWM(Pin(16,Pin.OUT))

> pwm.deinit()
> pwm.init()

buzzer=buzzer.Buzzer(pwm)
buzzer.play(score=Musical_Score,tempo=90,freq_multiple=1,output=1)
```

**Comment by Wind-stormger** [comment]
> 

Thanks for submitting the issue.
I need to know what version of the micropython firmware you are currently using.
This is a great help in understanding your problem as soon as possible.

**Comment by Wind-stormger** [comment]
I have tried your code in micropython firmware version v1.18-99-g203ec8ca7 (2022-02-06).
No need for extra `pwm.deinit()` and `pwm.init() `to hear the sound.

**Comment by vahithosan** [comment]
Before I used Micropython firmware v1.18 (2022-01-17).bin 
I installed v1.18-99-g203ec8ca7 verion after your answer. Works perfect. Thanks.
